name: LobbyPlugin
version: 1.0.0
author: Nevah5
main: dev.nevah5.mc.lobbyplugin.LobbyPlugin
api-version: 1.19
commands:
  build:
    description: Toggle building in world
    usage: /<command>
    permission: lobby.build
  cc:
    description: Clears the chat
    usage: /<command>
    permission: lobby.chat.clear
  spawn:
    description: Teleports the player to the spawn
    usage: /<command>
permissions:
  lobby.*:
    description: "The permissions for lobby commands and tools."
    children:
      lobby.build: true
      lobby.chat.colors: true
      lobby.chat.clear: true