name: LobbyPlugin
version: 1.0.0
author: Nevah5
main: dev.nevah5.mc.lobbyplugin.LobbyPlugin
api-version: 1.19
commands:
  build:
    description: Toggle building in world
    usage: /build
    permission: lobby.build
permissions:
  lobby.*:
    description: "The permissions for lobby commands and tools."
    children:
      lobby.build: true
      lobby.chat.colors: true